import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import Header from '../components/header';

import socket from '../utils/socket';
import { useStore } from 'zustand';

import { useState } from 'react';

socket.on('message', (text) => {
  console.log(text);
});

socket.on('hello', (text, callback) => {
  console.log(text);
  callback('got it');
});

const Home: NextPage = () => {
  const [message, setMessage] = useState('');

  const bears = useStore((state) => state.bears);
  const increasePopulation = useStore((state) => state.increasePopulation);

  return (
    // <div className={styles.container}>
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <h1>Home</h1>

      <input type="text" onChange={(e) => setMessage(e.target.value)} />
      <button onClick={() => socket.emit('message', message)}>Send</button>

      <h2>Create a lobby</h2>
      <Link href="/create-game">Create</Link>

      <h1>{bears}</h1>
      <button onClick={increasePopulation}>Add Bear</button>
    </>
    // </div>
  );
};

export default Home;
export { socket };
