import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import Header from '../components/header';

import { io } from 'socket.io-client';
import { useState } from 'react';

const socket = io('ws://localhost:8800', {
  extraHeaders: {
    'Access-Control-Allow-Origin': '*',
  },
});

socket.on('message', (text) => {
  console.log(text);
});

socket.on('hello', (text, callback) => {
  console.log(text);
  callback('got it');
});

const Home: NextPage = () => {
  const [message, setMessage] = useState('');
  return (
    // <div className={styles.container}>
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <h1>Home</h1>

      <input type="text" onChange={(e) => setMessage(e.target.value)} />
      <button onClick={() => socket.emit('message', message)}>Send</button>
    </>
    // </div>
  );
};

export default Home;
